### ISSUE TITLE
Using pipeline with Ops Manager SAML auth

### ISSUE THREAD

**Issue by findneville** [pivotal-cf/bbr-pcf-pipeline-tasks#12]
Hi.. Our Ops Manager is SAML authenticated.. 

Can you provide some information on how we would go about exporting the Ops Manager settings in such as scenario?

**Comment by ChunyiLyu** [comment]
Hi @findneville,

Sorry for the delayed response. Our task currently is not compatible with a SAML authenticated Ops Manager. I think exporting the OM setting would also depend on how the SAML is set up. For more information, I recommend asking this question in the #pcf-releng channel in Pivotal slack. The release engineering team should have more insights on how to proceed. I will close the issue for now. Feel free to reopen for further questions.

Cheers,
Chunyi && @MirahImage
