### ISSUE TITLE
Question:  OpsManager configured with SAML Authentication

### ISSUE THREAD

**Issue by aalksnin** [pivotal-cf/bbr-pcf-pipeline-tasks#15]
How do we backup OM installation settings if Ops Manager is configured with SAML Authentication?

Is there a way to get credentials to be used in Concourse automation pipeline to target Ops Manager in fully automated way?

Thank you!

**Comment by alamages** [comment]
Hello @aalksnin,

The concourse tasks we provide are not currently compatible with a SAML authenticated Ops Manager. I think exporting the OM settings also depend on how the SAML is set up. For more information, I recommend asking this question in the #pcf-releng channel in Pivotal slack. The release engineering team should have more insights on how to proceed. I will close the issue for now. Feel free to reopen for further questions.
