### ISSUE TITLE
failed to stream in to volume

### ISSUE THREAD

**Issue by akamalov** [pivotal-cf/bbr-pcf-pipeline-tasks#16]
* Concourse version: ```3.14.0```
* Deployment type (BOSH/Docker/binary): ```binary```
* Infrastructure/IaaS: ```VMware```
* Browser (if applicable): ```Chrome / Firefox```
* Did this used to work? ```Initial Test```

I am using https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/issues/14 pipeline to automate PCF ecosystem backup. Out of three jobs running in parallel , job #1 (```bbr-backup-ert```) and job #2 (```export-om-installation```) finish successfully. However, job #2 (```bbr-backup-director```) errors out with the following message:

```failed to stream in to volume```.

This is it. No more information. Won't tell me why it failed.

![image](https://user-images.githubusercontent.com/7885257/41778562-14c98378-75fd-11e8-9243-2cd538c4f88f.png)

![image](https://user-images.githubusercontent.com/7885257/41778584-20696d38-75fd-11e8-9f9a-fdf83c302fe6.png)

How can I troubleshoot this? Any ideas?

Thanks a lot.

Alex

**Comment by akamalov** [comment]
I hope Pivotal will pick up this ticket and it won't meet the fate of abandonment just like the rest of the tickets filed here..Honestly, why even have ```Issues``` feature available if no one is looking at it...

**Comment by gcapizzi** [comment]
Hi @akamalov ! It looks like your backup succeeded, but it's failing to upload the artifact to your `director-backup-bucket`. What you are seeing is a [Concourse error](https://github.com/concourse/baggageclaim/blob/master/api/volume_server.go#L26), not a BBR error. I would suggest to check the configuration for the bucket in your Concourse pipeline to make sure it's correct. If you believe your configuration is correct, then you might have to get in touch with the Concourse team which maintains the [S3 resource](https://github.com/concourse/s3-resource).

Thanks!
Giuseppe && @MirahImage

**Comment by akamalov** [comment]
Thanks so much @gcapizzi
