### ISSUE TITLE
use ensure vs on_failure and use cache directories

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal-cf/bbr-pcf-pipeline-tasks#18]
Shouldn't the backup in the container always be cleaned up (on failure and on success)? The `ensure` task item runs in both scenarios. Also, using cached folders avoids copying the backup from one container task to another. If you hijack the containers you can see it is indeed copied. 

I can create a pull request for this: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/compare/master...patrickhuber:master but never received customer feedback that it was working. My local tests showed that it worked as expected.

**Comment by glestaris** [comment]
@patrick-huber-pivotal I've heard of this issue before. Can you please elaborate on why not cleaning up the backup artifacts in the Concourse jobs is a problem?

cc @jama-pivotal for context

**Comment by glestaris** [comment]
I'll close this for now due to lack of activity. Feel free to reopen :)

**Comment by patrick-huber-pivotal** [comment]
@glestaris sorry for the late response. Not cleaning up the artifacts is an issue for most customers because they take up disk space on the concourse worker and can easily blow out the available disk space. In the end, the pipeline is just a vehicle for moving the backups from bosh deployments to an external store like S3 or NFS, so there is little value in caching them in the pipeline container volumes. 

For each pipeline run, the backup for that run is stored. Garbage collection doesn't get to these fast enough especially if you are quickly iterating on a pipeline.
