### ISSUE TITLE
bbr-version

### ISSUE THREAD

**Issue by ryantakeuchi** [pivotal-cf/bbr-pcf-pipeline-tasks#23]
it doesn't look like `bbr-version` in `secrets.yml` is being used by a pipeline. should the version be controlled by a parameter or hardcoded using `tag: latest-final`

**Comment by MirahImage** [comment]
Thank you! We have corrected this by [removing the variable](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/commit/cb97e4047c015319fe35b8975a722810d2aa152e).

We recommend using the latest version of `bbr`. The sample pipeline gets the latest version from PivNet.

Best,
Mirah and @jamesjoshuahill
