### ISSUE TITLE
Ops Man export fails if someone else is logged in

### ISSUE THREAD

**Issue by findneville** [pivotal-cf/bbr-pcf-pipeline-tasks#24]
Just need to know if anyone has considered DELETE-ing all current sessions before starting the om export installation. 

My Ops Manager export installations fail when someone else is logged into Ops Manager. 

A simple "om curl DELETE /api/v0/sessions" should help avoid failed installation exports.

I maybe able to submit a PR for this if interested.

**Comment by glestaris** [comment]
Hey @findneville, we will check with the Ops Manager team on whether this is expected behaviour, and get back to you soon.

**Comment by MirahImage** [comment]
Hi @findneville, 

We've tried this on PCF 2.2, triggering our pipeline while logged in to Ops Manager, and were unable to reproduce the issue. Can you provide more details?

**Comment by findneville** [comment]
2.2 is cutting edge. You should be able to reproduce this in Pre 2.2 environments. 

Not sure if it is worth checking the opsman version and then applying some logic for backward compatibility. 

Thanks!
NEVILLE GEORGE

**Comment by jamesjoshuahill** [comment]
Hi @findneville 

Please could you tell us which version of PCF you see this issue with? And what is the error message in the `export-om-installation` job?

Thanks
Josh and @aclevername

**Comment by findneville** [comment]
We are running it on both 2.1 and 2.2 PCF environments. 

In the 2.1 environments, the pipeline fails with the following error when someone is logged in 

```
Using Client ID credentials
exporting installation
	
265 B / ? [--------------=----------------------------------------]   2.65% 0s 
could not execute "export-installation": failed to export installation: request failed: unexpected response
```

Running the om_cmd command manually will show you the error that "someone is already logged in. Run the API command to delete existing sessions"

**Comment by findneville** [comment]
Sorry had to do a lot of edits to the previous comment to figure out the whole <code> structure within the comment :(

**Comment by MirahImage** [comment]
Thank you, we have reproduced the behaviour.

**Comment by findneville** [comment]
Interestingly.. I thought it would be nice to clean out all sessions before I ran the other commands and it looks like that failed too. My `clientuser` has `opsman.admin` scope and authority. It still complains that I have no rights.

```
myuser } (~/) om -k -c clientuser -s clientpwd -t https://opsman/uaa curl -p https://opsman/api/v0/sessions -x DELETE
Status: 403 Forbidden
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Wed, 22 Aug 2018 22:24:10 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: ab3ea649-ca92-4e2d-a6de-ad28005a0a09
X-Runtime: 0.069540
X-Xss-Protection: 1; mode=block
{
  "errors": {
    "base": [
      "opsman.admin or opsman.user or opsman.full_control or opsman.restricted_control scope is required to perform this operation"
    ]
  }
}
could not execute "curl": server responded with an error
```

**Comment by aclevername** [comment]
Hi @findneville 

We created a client with `opsman.admin` scope and authorities:

```bash
$ uaac client get test_client
  scope: opsman.admin
  client_id: test_client
  resource_ids: none
  authorized_grant_types: client_credentials
  autoapprove:
  access_token_validity: 43200
  refresh_token_validity: 43200
  authorities: opsman.admin
  name: test_client
  signup_redirect_url:
  lastmodified: 1535028877726
```

Using this client we were able to log all users out:

```bash
$ om --skip-ssl-validation \
  --target https://pcf.example.com \
  --client-id test_client \
  --client-secret CLIENT_SECRET \
  curl \
  -x DELETE \
  -p /api/v0/sessions

Status: 200 OK
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 23 Aug 2018 13:07:53 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 60346ff6-2e17-41d1-b2ba-b95d549c7efd
X-Runtime: 0.247106
X-Xss-Protection: 1; mode=block
{}
```

Please could you explain why you want to use client credentials to export settings? If you use user credentials to export installation settings it succeeds even if the user is logged in to Ops Manager UI.

Best wishes
Jake and @jamesjoshuahill

**Comment by findneville** [comment]
I went back and checked the scope of the client I was using and it was not set to opsman.admin . I updated the scope of the user and I was able to logout sessions successfully. 

We use client credentials because Ops Manager access in our environments are SAML authenticated. Pretty sure that you cannot use user credentials when SAML authentication is enabled.

**Comment by findneville** [comment]
I think even for the 2.2 versions, I ran into problems with backing up when someone is already logged in.

Either way as a stop gap, I wrote a task that will delete logged in sessions before and after the bbr backups and it works for me. Would be happy to contribute if you feel that this needs to be integrated with the bbr backups

**Comment by ChunyiLyu** [comment]
Hi @findneville, 

thanks for opening this issue. The team has looked into this and decided that deleting logged-in sessions before exporting OM settings is not something we would like to recommend for our customers. We will let the opsmanger team aware of this request, and close this issue for now.

+ @pivotal-cf/pcf-ops-manager what's the reason for allowing one logged-in session when using client_id and client_secret? Is there any recommended workaround for this?

Cheers,
Chunyi && @MirahImage
