### ISSUE TITLE
Question: Is it Possible to Schedule The Pipeline

### ISSUE THREAD

**Issue by akamalov** [pivotal-cf/bbr-pcf-pipeline-tasks#25]
Greetings,

This is just a question: Is it even possible to schedule a pipeline run? For instance, I would like to do a periodic backup of PCF, let's say every Saturday morning at 02:00am. Will it be possible to do it, or should I be resorting to ```unpause``` and then ```pause``` using ```fly``` and  based on crontab ?

**Comment by jamesjoshuahill** [comment]
Hi @akamalov 

To schedule a job in Concourse you can use the [time resource](https://github.com/concourse/time-resource).

For example, [there is an example](https://github.com/concourse/time-resource#trigger-once-within-time-range) showing how to trigger a job once every night after midnight.

Best wishes
Josh
