### ISSUE TITLE
Example pipeline does not account for om client id / secret params

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/bbr-pcf-pipeline-tasks#31]
The [sample pipeline does not include param values for `client-id` or `client-secret` to be passed in for `om` auth.](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/pipeline.sample.yml#L11-L13), however the sample `secrets.yml` file [has those params defined](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/secrets.sample.yml#L7-L8). Maybe I'm missing something on this, though?

[Also it might not hurt to rename `client-id` and `client-secret` to `opsman-client-id` and `opsman-client-secret` just for consistency.](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/secrets.sample.yml#L3-L8)

EDIT: [it also appears some of the tasks don't allow for client-id and client-secret either](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/tasks/bbr-backup-pks/task.yml#L18-L20)

**Comment by MirahImage** [comment]
Hi @aegershman, 

Thank you for bringing this to our attention. The sample pipeline is actually intended to be more of a guide for how a pipeline which uses the sample tasks might look, rather than a complete and exhaustive pipeline. 

Regarding the issue in the EDIT (Some tasks not allowing for client-id and client-secret), could you point us towards which tasks don't allow these parameters?

Thank you, 
Mirah

**Comment by aegershman** [comment]
@MirahImage As for the client-id and client-secret, I was wrong about the tasks not including it. It just wasn't named as I was expecting (e.g., [om linux refers to it as `OM_CLIENT_ID` and `OM_CLIENT_SECRET`](https://github.com/pivotal-cf/om), but it's named as `CLIENT_ID` and `CLIENT_SECRET` in the `task.yml`) I'm sorry, my bad about that, it was just a naming thing && I totally missed that. [The sample pipeline doesn't include `CLIENT_ID/SECRET` as referenceable params, though it's really not a huge deal. It can be figured out.](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/pipeline.sample.yml#L32-L37)

I'm curious how generally backwards compatible you'd like this repo to be, while also accepting of new naming conventions && such? E.g., would you consider accepting PRs which make changes such as:

* Swapping the `CLIENT_ID/SECRET` naming to be consistent with om itself, e.g. `OM_CLIENT_ID`
* Changing references of ERT to PAS

**Comment by MirahImage** [comment]
Hi @aegershman, the tasks need to be backwards compatible, as they are actively consumed by users of bbr to regularly run backups in their pipelines.
