### ISSUE TITLE
Sample pipeline could allow for configurable `versioned_file` value

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/bbr-pcf-pipeline-tasks#32]
In the sample pipeline, [the default value for `om-backup-artifact` is `installation.zip`](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/pipeline.sample.yml#L105). It wouldn't hurt to parameterize that out into the `secrets.yml` (it's not a secret, but in lieu of a `params.yml` I just figure put it there?).

[The `ert-backup-bucket` resource could also be parameterized](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/pipeline.sample.yml#L114)

[Same with `director-backup-bucket`](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/pipeline.sample.yml#L123)

**Comment by alamages** [comment]
Hello @aegershman,

Sorry for not updating you earlier. We have created the sample pipelines to act as examples, they are not meant to be used directly to set pipelines. This is why we don't customize them further, users should copy them and tailor them towards their needs.

Thanks,
Emmanouil & @MModhaPivotal
