### ISSUE TITLE
Consider versioning these tasks

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/bbr-pcf-pipeline-tasks#34]
In order to allow consumers to consume this repository directly as a Concourse resource without being broken when non-passive changes are made, have you considered versioning these tasks?

Or if the tasks aren't going to be versioned, should these tasks be treated strictly as "reference tasks" not designed for direct consumption?

Surely there is going to come a day when these tasks will no longer be backwards compatible with every version of PAS/Opsmgr/PKS/etc. Perhaps it would be too much management overhead to maintain all different task compatibilities for different versions of products; [case in point, the `pcf-pipelines` project has to maintain all these compatibility matrices and such](https://github.com/pivotal-cf/pcf-pipelines). But then again, without version pinning, people using different product combinations will eventually be broken; naming conventions will eventually change (case in point, ERT is now PAS), etc.

**Comment by ChunyiLyu** [comment]
Hi @aegershman,

Thanks for the input! That is a very good point. However, maintaining different versions of each tasks would require more effort/costs at testing. I think for now, we will keep having one stable version of all tasks, until it gets costly to maintain backwards compatibility. 

Cheers,
Chunyi

**Comment by aegershman** [comment]
I understand 👍 ... Still, I'm going to kvetch a little more, then I'll drop it:

The reason I make a fuss about it is because this is basically the only maintained BBR automation out there (maybe I'm looking in wrong places?). Lots of people/companies have open sourced their concourse tasks/resources for app dev, platform automation, metrics collections, etc., and so there are many ideas to draw from and expand upon. It appears this repository is the only guidance out there for BBR automation, [and it's a little beholden to it's existing self](#35) due to naming conventions and such.

_with all this said..._ I don't mean to sound pushy or too critical; I respect your decisions, I trust you all enough to have this code running in our prod foundations, and I appreciate the work you all are doing.

**Comment by glestaris** [comment]
Hey @aegershman, we appreciate the feedback. Let me add a bit more colour to @ChunyiLyu's response.

The aim of this repo is to help PCF platform engineers automate the taking of a full backup of a PCF foundation. To this extent, your engagement with this project is highly appreciated as it means that you are finding value in this work.

In staying true to our aim, we are currently seeking ways to be involved in other, similar, efforts within PCF such as the successor of [PCF Pipelines](https://github.com/pivotal-cf/pcf-pipelines). That's not to say that this repo will be deprecated any time soon, but we are examining ways to help platform engineers automate things (e.g.: backups and upgrades) in a unified and consistent way. Hence, while we are figuring out what the future of PCF Pipelines will look like, we are reducing our investment in this project.

Nevertheless, we are still interested in the use cases and problems with this project as this would be amazing input for the future shape and form of PCF Pipelines and the BBR Backup Pipeline tasks. Would you be interested in spending some time with us to describe how you use the BBR Pipeline tasks and what are the limitations/issues you see?
