### ISSUE TITLE
BBR Backup using Jumpbox - OpsMgr or non-Concourse Worker

### ISSUE THREAD

**Issue by simmyxavier** [pivotal-cf/bbr-pcf-pipeline-tasks#4]
The current pipeline is assuming the Concourse Worker is able to talk to OpsMgr, Director and ERT for backing up using BBR. Any Pipelines available for doing a BBR Backup using Jumpbox - either OpsMgr acting as Jumpbox or a Non-Concourse Worker. We have firewall restrictions and only Ops Mgr and one other utility VM is allowed to talk to the Director and Deployments in PCF Foundations. We do not have a concourse worker in each of our foundations due to network and security reasons.

**Comment by glestaris** [comment]
[BBR  v1.2.7](https://docs.cloudfoundry.org/bbr/bbr-rn.html#1.2) which is coming out later today has support for the `BOSH_ALL_PROXY` (https://bosh.io/docs/cli-tunnel/) environment variable. Would that work for you @simmyxavier?
