### ISSUE TITLE
Deprecate ERT tasks

### ISSUE THREAD

**Issue by jamesjoshuahill** [pivotal-cf/bbr-pcf-pipeline-tasks#46]
In the [v1.1.0 release notes](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/releases/tag/v1.1.0) we announced that the ERT tasks are deprecated and that we will remove them in a future version. Removing `bbr-backup-ert` and `bbr-cleanup-ert` will be a breaking change and we will cut a major release.

If you use these tasks to back up ERT, then you should consider pinning to version 1.0.0, see [Pinning to a version](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/tree/v1.1.0#pinning-to-a-version).

If you use these tasks to back up PAS, then you should switch to `bbr-backup-pas` and `bbr-cleanup-pas`.

Please comment in this issue if you have any objections.

@terminatingcode and Josh

**Comment by alamages** [comment]
The tasks were removed as part of https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/pull/63

A new major version is released without the ert tasks: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/releases/tag/v2.0.0
