### ISSUE TITLE
BBR unlocking bbr-usage-servicedb on backup_restore - PCF 2.3.4

### ISSUE THREAD

**Issue by sarojraju** [pivotal-cf/bbr-pcf-pipeline-tasks#48]
[bbr] 2019/03/26 16:07:08 ERROR - Error unlocking bbr-usage-servicedb on backup_restore/78a03107-5bab-4fb4-8308-0a4d5c60bb8f.
[bbr] 2019/03/26 16:07:08 INFO - Finished running post-backup-unlock scripts.
2 errors occurred:
error 1:
1 error occurred:
error 1:
Error attempting to run pre-backup-lock for job bbr-usage-servicedb on backup_restore/78a03107-5bab-4fb4-8308-0a4d5c60bb8f: + exec /var/vcap/jobs/bbr-usage-servicedb/bin/lock
+ export PATH=/var/vcap/packages/cf-cli-6-linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ PATH=/var/vcap/packages/cf-cli-6-linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ cf api https://api.sys-xxx-xxx.xxx.xxx.net --skip-ssl-validation
+ echo 'Using cf auth to authorize'
+ set +x
Credentials were rejected, please try again. - exit code 1error 2:
1 error occurred:
error 1:
Error attempting to run post-backup-unlock for job bbr-usage-servicedb on backup_restore/78a03107-5bab-4fb4-8308-0a4d5c60bb8f: + exec /var/vcap/jobs/bbr-usage-servicedb/bin/unlock
+ export PATH=/var/vcap/packages/cf-cli-6-linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ PATH=/var/vcap/packages/cf-cli-6-linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ sleep 120
+ cf api https://api.xxxx.net --skip-ssl-validation
+ echo 'Using cf auth to authorize'
+ set +x
Credentials were rejected, please try again. - exit code 1
It is recommended that you run `bbr backup-cleanup` to ensure that any temp files are cleaned up and all jobs are unlocked.

**Comment by gmrodgers** [comment]
Hey @sarojraju 

Could you provide some steps or context to reproduce this error?  What version of PAS are you running this task against?  This is the deployment backup task yes? What was the result after running `bbr deployment backup-cleanup` against your deployment?

Best,
Glen

**Comment by terminatingcode** [comment]
Hi @sarojraju,
As we haven't heard anything else on this so we're going to close this for now. If you have more information regarding your environment, please feel free to re-open the issue with the relevant information.
