### ISSUE TITLE
Add option to not specify any tag for worker so worker from default pool is selected

### ISSUE THREAD

**Issue by richard-repko** [pivotal-cf/bbr-pcf-pipeline-tasks#5]
Can you please add option in pipeline/secrets yml to not specify any tag for worker so worker from default pool is selected?

**Comment by ChunyiLyu** [comment]
Hi @richard-repko, thanks for the feedback. We provide the pipeline definitions as a sample. Please edit those definitions if you wish to customize :)

Thanks,
Chunyi && @gcapizzi
