### ISSUE TITLE
tar: director-backup.tar: Cannot write: No space left on device

### ISSUE THREAD

**Issue by krish118** [pivotal-cf/bbr-pcf-pipeline-tasks#50]
Hi,
I am getting the error "tar: director-backup.tar: Cannot write: No space left on device, tar: Error is not recoverable: exiting now", when running the pipeline.
I have increased the space for Bosh Director in PAS tile, But still getting the same error.
Could any one help me in understanding where exactly, it was loading the temporary ".tar" files, before moving them to Storage Account.

Thanks in advance.

**Comment by alamages** [comment]
Hello @krish118,

Can you please reach out to #pcf-backup-restore on Pivotal slack for this?

When you do, can you also please provide the following:
- Version of PCF
- Logs of the failed `bbr director backup` run from concourse build.

Thanks!

**Comment by aclevername** [comment]
Hi @krish118 

We're going to close this issue due to inactivity, if you are still experiencing problems due to this and have the information referenced above then feel free to reopen.
