### ISSUE TITLE
Dockerfile does NOT download a valid om command

### ISSUE THREAD

**Issue by erikonsmt** [pivotal-cf/bbr-pcf-pipeline-tasks#57]
Docker container created by the Dockerfile at bbr-pcf-pipeline-tasks/docker does NOT contain any valid om commands. This is the same for the Docker image pcfplatformrecovery/bbr-pcf-pipeline-tasks at Docker Hub, which seems to be updated recently. I think this is because the download url list, https://api.github.com/repos/pivotal-cf/om/releases/latest, is updated.

Hope this problem to be resolved.

**Comment by terminatingcode** [comment]
Hi @erikonsmt 
Thanks for reporting. We had a bump in one of our dependencies that kicked this off. We've resolved the issue as of [this commit](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/commit/796c6009eb5b87594c9b422a68686d53f0584543).

This should now be resolved and the latest pull of the docker image with the tag `final` should contain `om`.
