### ISSUE TITLE
Do we can call all params in parameters file instead of pipeline file

### ISSUE THREAD

**Issue by krishna-v444** [pivotal-cf/bbr-pcf-pipeline-tasks#61]
We were unable to call all parameters, like SA details instead of calling in pipeline.yml file.
Is there a way to call, all of them in params.yml file?

Thanks in advance.

**Comment by alamages** [comment]
Hello @krishna-v444 ,

Sorry but I do not understand the question. Is there an issue with the tasks? Can you provide more details/description on your issue? Thanks!

**Comment by alamages** [comment]
Hello @krishna-v444, I am closing this issue. Please feel free to re-open with more details and description. Thanks.
