### ISSUE TITLE
Pull for each minute

### ISSUE THREAD

**Issue by gitmedur** [pivotal-cf/bbr-pcf-pipeline-tasks#72]
Hi
Running bbr pipelines in a PKS environment. Because of docker pull rate limits, i moved the pivnet-resource image to internal registry. The backups are running according to a schedule by using a time resource. When i look at my internal registry logs, i see that pivnet-resource:latest is pulled once in each minute of the day..
This is the pivnet resource:
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: $internal_registry:443/pks/pivnet-resource
    tag: latest-final
resources for bbr repo and bbr-release:
resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:    
    uri: http://$internal_git/bbr-pcf-pipeline-tasks-2.1.0.git
    #private_key: ((git-private-key))
    branch: test
    #tag_filter: ((bbr-pipeline-tasks-repo-version))

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore

My time resource:
- name: trigger-daily-between-1am-and-2am
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM
    location: Asia/Istanbul
Job for om exports:
jobs:
- name: export-om-installation
  serial: true
  plan:
  - get: trigger-daily-between-1am-and-2am
    trigger: true
  - in_parallel:
    - get: bbr-release
    - get: bbr-pipeline-tasks-repo
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      <<: *opsman_credentials
    #  SKIP_SSL_VALIDATION: ((skip-ssl-validation))
    #  OPSMAN_URL: ((opsman-url))
    #  OPSMAN_USERNAME: ((opsman-username))
    #  OPSMAN_PASSWORD: ((opsman-password))
  - put: om-backup-bucket
    params:
      file: om-installation/installation_*.zip

So wondering what triggers a pull from internal registry each minute..Any ideas?

**Comment by fnaranjo-vmw** [comment]
Hello @gitmedur 

According to the [official Resource Types docs](https://concourse-ci.org/resource-types.html#schema.resource_type.check_every):

> check_every: duration
Default 1m. The interval on which to check for new versions of the resource type. Acceptable interval options are defined by the time.ParseDuration function.
https://concourse-ci.org/resource-types.html#schema.resource_type.check_every

You could change it to run checks less frequently. Every ```5h``` in the following example:
```
name: pivnet
type: docker-image
check_every: 5h
source:
    repository: $internal_registry:443/pks/pivnet-resource
    tag: latest-final
```

But I suggest that you take a look at these links:
They might help you solve the rate limit issue without so much manual work.
- [Implement mitigations for stricter Docker Hub rate limits](https://github.com/concourse/concourse/issues/6073)
- [Concourse v6.7.0 Release Notes](https://github.com/concourse/concourse/releases/tag/v6.7.0)
- [Concourse v6.7.1 Release Notes](https://github.com/concourse/concourse/releases/tag/v6.7.1)
----
Closing this, but please feel free to reopen it if the suggested solution doesn't work for you.

Have a nice day!
