### ISSUE TITLE
Support client ID and secret for accessing Opsman 

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/bbr-pcf-pipeline-tasks#8]
Add support for using client ID and secret to access opsman instead of username and password.

**Comment by matthewfischer** [comment]
+1

**Comment by glestaris** [comment]
This sounds useful. Thanks for reporting.

@matthewfischer or @labrown would any of you be interested in making a PR?

**Comment by labrown** [comment]
Sorry, I'm not in a position to contribute at this time.

**Comment by findneville** [comment]
I put in a PR for this request https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/pull/21

**Comment by glestaris** [comment]
Thanks a lot @findneville! We will review/merge soon.

**Comment by ChunyiLyu** [comment]
@labrown We have merged the PR from @findneville which adds support for `CLIENT_ID` and `CLIENT_PASSWORD` in all of our tasks. Feel free to update your pipeline configurations and try it out. 

Cheers,
Chunyi
